// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
:projectid: guide-spring-boot
:page-duration: 30 minutes
:page-releasedate: 2018-11-17
// INSTRUCTION: Provide a description for the guide index page.
:page-description: Learn how to deploy a Spring Boot application in Open Liberty.
// INSTUCTION: Please provide relevant tags, try to avoid inventing new ones, tags where there is 1 guide for the tag isn't useful.
:page-tags: []
// INSTRUCTION: Specify the unique name of the guide that is used in the permalink.  For example below, it is rest-service
:page-related-guides: ['rest-intro']
// INSTRUCTION: Specify the slug in the website. This must be unique.
:page-permalink: /guides/spring-boot-guide
// INSTRUCTION: You should have this to source the common page elements, clone git@github.com:OpenLiberty/guides-common.git
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
// INSTRUCTION: You can't have a new line between the attributes and the title.
// The details of what to fill in for this template are in the comments. So, read the source for this template to see the comments.
//
// Example title: Creating a RESTful web service
= Deploying a Spring Boot Application

Learn how to deploy a Spring Boot application on a Liberty server.

== What you'll learn
Spring Boot is an open source Java-based framework used to develop microservices. You will learn how to deploy a Spring Boot application in Open Liberty and how to build an Open Liberty Docker image to run the Spring Boot application.

The starting point of this guide will be the finished application from Spring's https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot] guide.
 Please first go through that guide if you are not familiar with Spring Boot. Note that Java 8 is required to run this project.

// Add this getting started section to your guide if it is applicable. Use the following include to pull in the git clone instructions from the guides-common repo.
[role='command']
include::{common-includes}/gitclone.adoc[]

== Building and running the Spring Boot application
You will first need to build the initial Spring Boot application into an executable jar file. Navigate to the `start` directory and run the Maven package command.

[role='command']
----
mvn package
----

You can now run the application in the embedded Tomcat web-container by executing the newly built jar file.

[role='command']
----
java -jar target/gs-spring-boot-0.1.0.jar
----

Notice that the console output will display that the application is running in Tomcat on port 8080. Now access the application at the following URL: http://localhost:8080/hello[^].


You should see the following output displayed in your browser:
[role='no_copy']
----
Greetings from Spring Boot!
----

When you need to stop the application, simply press `CTRL+C` in the shell session where you ran the application.


== Running the Spring Boot application on Open Liberty

Next, you will run the Spring Boot application on Open Liberty by updating the `pom.xml`.

The [hotspot file=0]`pom.xml` has already been created for you in this directory. 

[role="code_command hotspot file=0", subs="quotes"] 
---- 
#Update the `Maven POM` file.#
`pom.xml`
---- 
[role="edit_command_text"]
Add the [hotspot=libertyMavenPlugin file=0]`liberty-maven-plugin` to the [hotspot file=0]`pom.xml`.

pom.xml
[source, XML, linenums, role='code_column hide_tags=packageApp'] 
---- 
include::finish/pom.xml[]
---- 

The [hotspot=installAppPackages file=0]`<installAppPackages />` tag in the [hotspot file=0]`pom.xml` typically takes in the following parameters: `dependencies`, `project` or `all`. The default value being `dependencies`. 
However, in order to run the Spring Boot application the value should be set as `spring-boot-application`. This allows maven to package, thin, and copy the Spring Boot application `gs-spring-boot-0.1.0.jar` to the Liberty runtime application and shared library directories.

The [hotspot=configFile file=0]`<configFile />` tag specifies the location of the server configuration file.

[role="code_command hotspot file=1", subs="quotes"] 
---- 
#Create the `server.xml`.#
`src/main/liberty/config/server.xml`
---- 

The [hotspot=servlet file=1]`servlet` and [hotspot=springboot file=1]`springBoot` features are required for the Liberty server to run the Spring Boot application.
Since the  application was thinned, the `<springbootApplication />` location is set to [hotspot=location file=1]`thin-gs-spring-boot-0.1.0.jar`. 

server.xml
[source, XML, linenums, role='code_column'] 
---- 
include::finish/src/main/liberty/config/server.xml[]
---- 

Next, run the following command to build the application on Liberty:
[role='command']
```
mvn package
```

To run the application, start the server:
[role='command']
```
mvn liberty:start-server
```

Point your browser to the http://localhost:9080/hello[^] URL to access the application.


When you are finished checking out the application, stop the server:
[role='command']
```
mvn liberty:stop-server
```

== Package the Spring Boot application embedded with Open Liberty

You can update the `pom.xml` and the `server.xml` to package the Spring Boot application embedded with Open Liberty.

[role="code_command hotspot file=0", subs="quotes"] 
---- 
#Update the `Maven POM` file.#
`pom.xml`
---- 
[role="edit_command_text"]
Add the [hotspot=packageApp file=0]`<execution />` to the `pom.xml`.
 
finish/pom.xml
[source, XML, linenums, role='code_column'] 
---- 
include::finish/pom.xml[]
---- 

The [hotspot=include file=0]`<include />` tag of this execution is specified to `minify`, `runnable`. The `runnable` value allows the application to be generated as a runnable `jar` file and the `minify` value packages only what you need from your configuration files without bundling the entire `Liberty` install.

The [hotspot=packageFile file=0]`<packageFile />` tag specifies that the application will be generated as `GSSpringBootApp.jar`. 


[role="code_command hotspot=sbThin file=1", subs="quotes"] 
---- 
#Update the `server.xml`.#
`src/main/liberty/config/server.xml`
---- 
[role="edit_command_text"]
Update the `location` of the Spring Boot application to [hotspot=location file=1]`thin-gs-spring-boot-thin.jar`.
 
server.xml
[source, XML, linenums, role='code_column'] 
---- 
include::finish/src/main/liberty/config/server.xml[]
---- 

Next, run the repacked Spring Boot application with Liberty. This jar was defined previously in the [hotspot file=0]`pom.xml`.

[role='command']
```
java -jar target/GSSpringBootApp.jar
```

Point your browser to the http://localhost:9080/hello[^] URL to access the application.

When you need to stop the application, simply press `CTRL+C` in the shell session where you ran the application.

== Deploying the application to Docker
You will build an Open Liberty Docker image to run the Spring Boot application. Using Docker, you can run your thinned application with a few simple commands.
For more information on using Open Liberty with Docker, see the https://github.com/OpenLiberty/guide-docker[Using Docker containers to develop microservices] guide.


Navigate to the `start` directory. 

[role="code_command", subs="quotes"] 
---- 
#Create the `Dockerfile`.#
`Dockerfile`
---- 

Dockerfile
[source, Text, linenums, role='code_column'] 
---- 
include::finish/Dockerfile[]
---- 

This Dockerfile is written in two main stages. The first stage copies over the [hotspot=copyJar]`spring boot jar` that was generated into the [hotspot=OLimage1]`Open Liberty image` and thins the application.
The [hotspot=springBootUtility]`springBootUtility` function is ran with the parameter `thin` to create the thinned Spring Boot application. For more information about this function, you can check out the https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_command_sbutility.html[official springBootUtility page^]

The next stage downloads the [hotspot=OLimage2]`Open Liberty image` and copies over the `server` configuration file as well as the library cache [hotspot=libcache]`lib.index.cache` and thinned jar [hotspot=thinjar]`thin-gs-spring-boot-0.1.0.jar` generated from the thinned application created in the previous section. 

Next, build the Docker image with the following command.
[role='command']
```
docker build -t springboot .
```

To verify that the images are built, run the `docker images` command to list all local Docker images:

[role='command']
```
docker images
```

Your image, `springboot`, should appear in the list of all Docker images:
[role='no_copy']
```
REPOSITORY    TAG       IMAGE ID         CREATED           SIZE
springboot    latest    d3ffdaa81854     27 seconds ago    486MB
```

Execute the Docker `run` command to run your Spring Boot application in a Docker container.
[role='command']
```
docker run -d --name springBootContainer -p 9080:9080 -p 9443:9443 springboot
```

Before you access your application from the browser, run the `docker ps` command from the command line to make sure that your container is running and didn’t crash:
[role='command']
----
docker ps
----

You should see an entry like the following:
[role='no_copy']
----
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                            NAMES
e33532aa07d6        springboot          "/opt/ibm/docker/doc…"   7 seconds ago       Up 2 seconds        0.0.0.0:9080->9080/tcp, 0.0.0.0:9443->9443/tcp   springBootContainer
----

Point your browser to the http://localhost:9080/hello[^] URL to access the application.

=== Tearing down Docker container

To stop and remove your container, run the following commands from the command line:

[role='command']
```
docker stop springBootContainer
docker rm springBootContainer
```

== Great work! You're done!

You installed a basic Spring Boot application to run in Open Liberty.

include::{common-includes}/finish.adoc[]

