// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
:projectid: spring-boot-guide
:page-duration: 30 minutes
:page-releasedate: 2018-11-17
// INSTRUCTION: Provide a description for the guide index page.
:page-description: Learn how to deploy a Spring Boot application in Open Liberty.
// INSTUCTION: Please provide relevant tags, try to avoid inventing new ones, tags where there is 1 guide for the tag isn't useful.
:page-tags: ['Spring Boot', 'Maven']
// INSTRUCTION: Specify the unique name of the guide that is used in the permalink.  For example below, it is rest-service
:page-related-guides: ['']
// INSTRUCTION: Specify the slug in the website. This must be unique.
:page-permalink: /guides/spring-boot-guide
// INSTRUCTION: You should have this to source the common page elements, clone git@github.com:OpenLiberty/guides-common.git
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
// INSTRUCTION: You can't have a new line between the attributes and the title.
// The details of what to fill in for this template are in the comments. So, read the source for this template to see the comments.
//
// Example title: Creating a RESTful web service
= Deploying a Spring Boot Application

Learn how to deploy a Spring Boot application on a Liberty server.

== What you'll learn
You will learn how to deploy a Spring Boot application in Open Liberty without modification and how to use the Spring Boot utility
 thin task to create a thin jar and indexed library for deploying on a Liberty server in Docker.
 The starting point of this guide will be the finished application from Spring's https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot] guide.
 Please first go through that guide if you are not familiar with Spring Boot. Note that Java 8 is required to run this project.

// Add this getting started section to your guide if it is applicable. Use the following include to pull in the git clone instructions from the guides-common repo.
[role='command']
include::{common-includes}/gitclone.adoc[]

== Building and running the Spring Boot app
You will first need to build the initial Spring Boot application into an executable jar file. Navigate to the `start/springBootApp` directory and run the Maven package command.

[role='command']
----
mvn package
----

You can now run the application in the embedded Tomcat web-container by executing the newly built jar file.

[role='command']
----
java -jar target/gs-spring-boot-0.1.0.jar
----

Notice that the console output will display that the application is running in Tomcat on port 8080. Now access the application at the following URL: http://localhost:8080/hello[^].


You should see the following output displayed in your browser:
[role='no_copy']
----
Greetings from Spring Boot!
----

When you need to stop the application, simply press `CTRL+C` in the shell session where you ran the application.


== Running the spring boot app on Liberty

Next, navigate to the `start/openLiberty` directory. 

The [hotspot file=0]`pom.xml` has already been created for you in this directory and is configured to copy the Spring Boot application to the Liberty server.
The [hotspot=liberty-maven-plugin file=0]`liberty-maven-plugin` in the `pom.xml` downloads  Liberty and the [hotspot=copy_file file=0]`<copy />` tag copies the Spring Boot application to the [hotspot=copy-dest file=0]`<wlp..>` destination path.

start/openLiberty/pom.xml
[source, XML, linenums, role='code_column hide_tags=copyright'] 
---- 
include::start/openLiberty/pom.xml[]
---- 

The [hotspot=servlet file=1]`servlet` and [hotspot=springboot file=1]`springBoot` features are configured in the [hotspot file=1]`server.xml`.

server.xml
[source, XML, linenums, role='code_column'] 
---- 
include::finish/openLiberty/src/main/liberty/config/server.xml[]
---- 

Next, run the following command to build the application on Liberty:
[role='command']
```
mvn package
```

To run the application, start the server:
[role='command']
```
mvn liberty:start-server
```

Point your browser to the http://localhost:9080/hello[^] URL to access the application.


When you are finished checking out the application, stop the server:
[role='command']
```
mvn liberty:stop-server
```

== Thinning the spring boot application on Liberty

You can update the `pom.xml` and the `server.xml` to separate the application code from the dependency jars, making it more efficient to deploy new versions of the application.

[role="code_command hotspot=thin file=0", subs="quotes"] 
---- 
#Update the `pom.xml`.#
`openLiberty/pom.xml`
---- 
[role="edit_command_text"]
Remove the  `<copy />` tag and replace it with the [hotspot=thin file=0]`<exec />` tag.
 
finish/openLiberty/pom.xml
[source, XML, linenums, role='code_column hide_tags=copyright'] 
---- 
include::finish/openLiberty/pom.xml[]
---- 

The [hotspot=thin file=0]`<exec />` tag in  the [hotspot file=0]`pom.xml` executes the [hotspot=40 file=0]`springBootUtility` command to create thin Spring Boot applications and library caches that can be deployed on Liberty.
The [hotspot=targetThinAppPath file=0]`--targetThinAppPath` option specifies the path used to save the thin application file which we will rename in the [hotspot file=1]`server.xml`.

[role="code_command hotspot=sbThin file=1", subs="quotes"] 
---- 
#Update the `server.xml`.#
`openLiberty/server.xml`
---- 
[role="edit_command_text"]
Update the `location` of the Spring Boot application to [hotspot=sbThin file=1]`gs-spring-boot-thin.jar`.
 
server.xml
[source, XML, linenums, role='code_column'] 
---- 
include::finish/openLiberty/src/main/liberty/config/server.xml[]
---- 

Next, run the following command to rebuild the application and start the server:
[role='command']
```
mvn clean package
mvn liberty:start-server
```

Point your browser to the http://localhost:9080/hello[^] URL to access the application.

When you are finished checking out the application, stop the server:
[role='command']
```
mvn liberty:stop-server
```

== Run the repackaged spring boot application with Liberty

Next, run the repacked spring boot application with Liberty.

[role='command']
```
java -jar target/GSSpringBootApp.jar
```

Point your browser to the http://localhost:9080/hello[^] URL to access the application.

When you need to stop the application, simply press `CTRL+C` in the shell session where you ran the application.

== Deploying the application to Docker

The `springBootUtility` thin command discussed in the previous section is especially useful when deploying your application to a Docker
container. Using Docker, you can run this thin function and run your thinned application with a few simple commands.
For more information on using Open Liberty with Docker, see the https://github.com/OpenLiberty/guide-docker[Using Docker containers to develop microservices] guide.


Navigate to the `start` directory. 

[role="code_command", subs="quotes"] 
---- 
#Create the `Dockerfile`.#
`Dockerfile`
---- 

Dockerfile
[source, Text, linenums, role='code_column'] 
---- 
include::finish/Dockerfile[]
---- 

Next, build the Docker image.
[role='command']
```
docker build -t springboot .
```

Execute the Docker `run` command to run your Spring Boot application.
[role='command']
```
docker run -d --name springBootContainer -p 9080:9080 -p 9443:9443 springboot
```

Before you access your application from the browser, run the `docker ps` command from the command line to make sure that your container is running and didn’t crash:
[role='command']
----
docker ps
----

You should see an entry like the following:
[role='no_copy']
----
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                            NAMES
e33532aa07d6        springboot          "/opt/ibm/docker/doc…"   7 seconds ago       Up 2 seconds        0.0.0.0:9080->9080/tcp, 0.0.0.0:9443->9443/tcp   springBootContainer
----

Point your browser to the http://localhost:9080/hello[^] URL to access the application.

=== Tearing down Docker containers  

To stop and remove your container, run the following command from the command line:

[role='command']
```
docker stop springBootContainer
docker rm springBootContainer
```

== Great work! You're done!

You installed a basic Spring Boot application to run in Open Liberty.

include::{common-includes}/finish.adoc[]
