// Copyright (c) 2019 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide-multipane
:projectid: spring-boot
:page-duration: 15 minutes
:page-releasedate: 2018-09-05
:page-description: Learn how to deploy a Spring Boot application on Open Liberty.
:page-tags: ['Docker']
:page-related-guides: ['rest-intro', 'containerize']
:page-permalink: /guides/{projectid}
:common-includes: ../guides-common/
:source-highlighter: prettify
:page-seo-title: Deploying and running a Spring Boot Application on Open Liberty.
:page-seo-description: A tutorial on how to deploy and run a Spring Boot application without modification on Open Liberty docker or local Liberty server, and how to package it embedded with a Liberty server.
:guide-author: Open Liberty
= Deploying a Spring Boot Application

Learn how to deploy a Spring Boot application on a Liberty server without modification.

== What you'll learn
The starting point of this guide will be the finished application from Spring's https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot^] guide. Please first go through that guide if you are not familiar with Spring Boot. Note that Java 8 is required to run this project.

You will learn how to deploy a Spring Boot application on a Liberty server in Docker without modification by using the Spring Boot utility thin command `springBootUtility`, which stores the dependent library JARs of the application to the target library cache and packages the remaining application artifacts into a thin application JAR.

Next, you will learn how to run the Spring Boot application locally with a Liberty server, and how to package it embedded with a Liberty server.

[role='command']
include::{common-includes}/gitclone.adoc[]


== Building and running the Spring Boot application in embedded Tomcat
You will first need to build the initial Spring Boot application into an executable jar file. 
Navigate to the `start` directory and run the Maven package command.

[role='command']
----
cd start
mvn package
----

You can now run the application in the embedded Tomcat web-container by executing the newly built jar file.

[role='command']
----
java -jar target/gs-spring-boot-0.1.0.jar
----

Notice that the console output displays a message that the application is running in Tomcat on port 8080. 
[role='no_copy']
----
... INFO ... [ main] o.s.b.w.embedded.tomcat.TomcatWebServer : Tomcat started on port(s): 8080 (http) with context path ''
----
Now access the application at the following URL: http://localhost:8080/hello[^].


You should see the following output displayed in your browser:
[role='no_copy']
----
Greetings from Spring Boot!
----

When you need to stop the application, simply press `CTRL+C` in the shell session where you ran the application.

== Running the application in Docker container
You will build an Open Liberty Docker image to run the Spring Boot application. Using Docker, you can run your thinned application with a few simple commands.
For more information on using Open Liberty with Docker, see the https://openliberty.io/guides/containerize.html[Containerizing microservices^] guide.

Navigate to the `start` directory. 

[role="code_command", subs="quotes"] 
---- 
#Create the `Dockerfile`.#
`Dockerfile`
---- 

Dockerfile
[source, Text, linenums, role='code_column'] 
---- 
include::finish/Dockerfile[]
---- 

This Dockerfile is written in two main stages. For more information about multistage Dockerfiles, you can check out the https://docs.docker.com/develop/develop-images/multistage-build/[multi-stage builds page^] on the official Docker site.
The first stage copies over the Spring Boot application [hotspot=copyJar]`gs-spring-boot-0.1.0.jar` to a temporary directory [hotspot=7 file=0]`/staging`, 
and then use the Open Liberty [hotspot=springBootUtility]`springBootUtility` command to thin the application. 
For more information, you can check out the https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_command_sbutility.html[official springBootUtility page^].

The next stage downloads the [hotspot=OLimage2 file=0]`Open Liberty image`, copies the [hotspot=20]`server` 
configuration file, the Spring Boot dependent library JARs at [hotspot=libcache file=0]`lib.index.cache`, and 
the thin application [hotspot=thinjar file=0]`thin-gs-spring-boot-0.1.0.jar` which were generated in the first stage.

To get the Spring Boot application running, the Liberty server needs to be correctly configured.

[role="code_command hotspot file=1", subs="quotes"] 
---- 
#Create the `server.xml`.#
`src/main/liberty/config/server.xml`
---- 

The [hotspot=servlet file=1]`servlet` and [hotspot=springboot file=1]`springBoot` features are required for the Liberty server to run the Spring Boot application.  The application port is specified as [hotspot=httpport file=1]`9080`.

server.xml
[source, XML, linenums, role='code_column'] 
---- 
include::finish/src/main/liberty/config/server.xml[]
---- 

Next, build the Docker image with the following command.
[role='command']
```
docker build -t springboot .
```

To verify that the images are built, run the `docker images` command to list all local Docker images:

[role='command']
```
docker images
```

Your image `springboot` should appear in the list of all Docker images:
[role='no_copy']
```
REPOSITORY    TAG       IMAGE ID         CREATED           SIZE
springboot    latest    d3ffdaa81854     27 seconds ago    486MB
```

Now, you can run the Spring Boot application in a Docker container.
[role='command']
```
docker run -d --name springBootContainer -p 9080:9080 -p 9443:9443 springboot
```

Before you access your application from the browser, run the `docker ps` command to make sure that your container is running and didn’t crash:
[role='command']
----
docker ps
----

You should see an entry like the following:
[role='no_copy']
----
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                            NAMES
e33532aa07d6        springboot          "/opt/ibm/docker/doc…"   7 seconds ago       Up 2 seconds        0.0.0.0:9080->9080/tcp, 0.0.0.0:9443->9443/tcp   springBootContainer
----

Point your browser to the http://localhost:9080/hello[^] URL to access the application.

=== Tearing down Docker container

To stop and remove your container, run the following commands:

[role='command']
```
docker stop springBootContainer
docker rm springBootContainer
```

== Running the Spring Boot application on Open Liberty

Next, you will run the Spring Boot application on Open Liberty locally by updating the `pom.xml`.

The [hotspot file=0]`pom.xml` has already been created for you in this directory. 

[role="code_command hotspot file=0", subs="quotes"] 
---- 
#Update the `Maven POM` file.#
`pom.xml`
---- 
[role="edit_command_text"]
Add the [hotspot=libertyMavenPlugin file=0]`liberty-maven-plugin` to the [hotspot file=0]`pom.xml`.

pom.xml
[source, XML, linenums, role='code_column hide_tags=packageApp'] 
---- 
include::finish/pom.xml[]
---- 
The `liberty-maven-plugin` will download and install Open Liberty to the `target/liberty` directory.
The [hotspot=installAppPackages file=0]`<installAppPackages/>` tag in the [hotspot file=0]`pom.xml` typically takes in the following parameters: `dependencies`, `project`, `all` or in this case `spring-boot-project`. The default value being `dependencies`. 
However, in order to install the Spring Boot application to the downloaded Open Liberty, the value should be set as [hotspot=installAppPackages file=0]`spring-boot-project`. This allows maven to package, thin, and copy the Spring Boot application `gs-spring-boot-0.1.0.jar` to the Liberty runtime application and shared library directories.

To get the Spring Boot application running, the Liberty server needs to be correctly configured.
The [hotspot=configFile file=0]`<configFile/>` tag specifies the location of the server configuration file.

Create the server.xml if you didn't do in the previous section.
[role="code_command hotspot file=1", subs="quotes"] 
---- 
#Create the `server.xml`.#
`src/main/liberty/config/server.xml`
---- 

server.xml
[source, XML, linenums, role='code_column'] 
---- 
include::finish/src/main/liberty/config/server.xml[]
---- 

Next, run the following command to build the application on Liberty:
[role='command']
```
mvn package
```

To run the application, start the server:
[role='command']
```
mvn liberty:start-server
```

Point your browser to the http://localhost:9080/hello[^] URL to access the application.


When you are finished checking out the application, stop the server:
[role='command']
```
mvn liberty:stop-server
```

== Package the Spring Boot application embedded with Open Liberty

You can update the `pom.xml` to package the Spring Boot application embedded with Open Liberty.

[role="code_command hotspot file=0", subs="quotes"] 
---- 
#Update the `Maven POM` file.#
`pom.xml`
---- 
[role="edit_command_text"]
Add the [hotspot=packageApp file=0]`<execution/>` to the `pom.xml`.
 
finish/pom.xml
[source, XML, linenums, role='code_column'] 
---- 
include::finish/pom.xml[]
---- 

The [hotspot=include file=0]`<include/>` tag of this execution is specified to `minify`, `runnable`. The `runnable` value allows the application to be generated as a runnable `jar` file and the `minify` value packages only what you need from your configuration files without bundling the entire `Liberty` install.

The [hotspot=packageFile file=0]`<packageFile/>` tag specifies that the application will be generated as `GSSpringBootApp.jar`. 
Next, run the Maven package command:
[role='command']
```
mvn package
```

Next, run the repacked Spring Boot application with Liberty. This jar was defined previously in the [hotspot file=0]`pom.xml`.

[role='command']
```
java -jar target/GSSpringBootApp.jar
```

Point your browser to the http://localhost:9080/hello[^] URL to access the application.

When you need to stop the application, simply press `CTRL+C` in the shell session where you ran the application.


== Great work! You're done!

You have just run a basic Spring Boot application with Open Liberty.

include::https://raw.githubusercontent.com/OpenLiberty/guides-common/master/attribution.adoc[]

