// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//
:page-layout: guide
:projectid: spring-boot-guide
:page-duration: 30 minutes
:page-releasedate: 2018-11-17
// INSTRUCTION: Provide a description for the guide index page.
:page-description: Learn how to deploy a Spring Boot application in Open Liberty.
// INSTUCTION: Please provide relevant tags, try to avoid inventing new ones, tags where there is 1 guide for the tag isn't useful.
:page-tags: ['Spring Boot', '', 'Maven']
// INSTRUCTION: Specify the unique name of the guide that is used in the permalink.  For example below, it is rest-service
:page-related-guides: ['']
// INSTRUCTION: Specify the slug in the website. This must be unique.
:page-permalink: /guides/spring-boot-guide
// INSTRUCTION: You should have this to source the common page elements, clone git@github.com:OpenLiberty/guides-common.git
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
// INSTRUCTION: You can't have a new line between the attributes and the title.
// The details of what to fill in for this template are in the comments. So, read the source for this template to see the comments.
//
// Example title: Creating a RESTful web service
= Deploying a Spring Boot Application

Learn how to deploy a Spring Boot application on a Liberty server.
// Write no more than two sentences, or about fifty words with meaningful information on what the user can accomplish with this guide.
// Do not start the introduction with "This guide...".

== What you'll learn
You will learn how to deploy a Spring Boot application in Open Liberty without modification and how to use the Spring Boot utility
 thin task to create a thin jar and indexed library for deploying on a Liberty server in Docker.
 The starting point of this guide will be the finished application from Spring's https://spring.io/guides/gs/spring-boot/[Building an Application with Spring Boot] guide.
 Please first go through that guide if you are not familiar with Spring Boot. Note that Java 8 is required to run this project.

// Add this getting started section to your guide if it is applicable. Use the following include to pull in the git clone instructions from the guides-common repo.
include::{common-includes}/gitclone.adoc[]

== Building and running the application in embedded Tomcat
You will first need to build the initial Spring Boot application into an executable jar file. Move to the `start` directory and run the Maven package command.

----
cd start
mvn package
----

You can now run the application in the embedded Tomcat web-container by executing the newly built jar file.
----
java -jar target/gs-spring-boot-0.1.0.jar
----

Notice that the console output will display that the application is running in Tomcat on port 8080. Now access the application at the following URL:

----
http://localhost:8080
----

You should see the following output displayed in your browser:

----
Greetings from Spring Boot!
----



== Deploying the application to Open Liberty

Download and unzip the latest stable release of Open Liberty here: https://openliberty.io/downloads/

Move to your Open Liberty `wlp/bin` directory and create a basic Liberty server called `springBoot`.

----
cd wlp/bin
./server create springBoot.
----

Next move to the new server directory `wlp/usr/servers/springBoot` and edit the server.xml file by adding the following features under the featureManager stanza.

----
<feature>servlet-4.0</feature>
<feature>springBoot-2.0</feature>
----

=== Quick deploying the application to dropins

You can quickly install the application by simply adding it to the dropins directory. Navigate to `dropins` and create a directory named `spring`.

----
cd dropins
mkdir spring
----

Copy the `gs-spring-boot-0.1.0.jar` file created by the Maven package command into the spring directory.

----
cp <git-rep-root>/start/target/gs-spring-boot-0.1.0.jar ./spring
----

Move to the `wlp/bin` directory and start the Liberty server.

----
 ./server start springBoot
----

Now access the application at the following URL:

----
http://localhost:9080
----

You should see the following output displayed in your browser:

----
Greetings from Spring Boot!
----


=== Installing your application in the apps directory
Due to restrictions on use of the dropins directory you may need to run your application out of the apps directory.
To do this, navigate to the Open Liberty server directory and move the application from `dropins/spring` to `apps`.

----
mv dropins/spring/gs-spring-boot-0.1.0.jar apps
----

Now add the following to your server.xml

----
  <springBootApplication location="gs-spring-boot-0.1.0.jar"/>
----

The change will be detected automatically without restarting the server. Refresh the browser page and make sure the same output is displayed.

----
Greetings from Spring Boot!
----

== Thinning the application with the springBootUtility thin task

The jar generated for a spring boot application contains various supporting artifacts that can make it very large.
If you are updating your application frequently in a cloud environment, pushing a large application can be resource intensive.
You can run the `springBootUtility thin` command to separate the application code from the dependency jars, making it more efficient to deploy new versions of the application.

Move to the `wlp/bin` directory and run the following command:

----
./springBootUtility thin \
   --sourceAppPath=../usr/servers/springBoot/apps/gs-spring-boot-0.1.0.jar \
   --targetThinAppPath=../usr/servers/springBoot/apps/gs-spring-boot-0.1.0.thin.jar \
   --targetLibCachePath=../usr/shared/resources/lib.index.cache
----

This will create a thinned version of the application and generate a cache directory in `wlp/usr/shared/resources` that contains the separated dependency jars.

Now, navigate to the springBoot server directory `wlp/usr/servers/springBoot` and edit the server.xml to point to the new thinned jar.

----
  <springBootApplication location="gs-spring-boot-0.1.0.thin.jar"/>
----

Move back to the `wlp/bin` directory and start the Liberty server with the `--clean` option. This
will ensure that the `lib.index.cache` from the thin function is used.

----
./server start springBoot --clean
----

As before, you can ensure that the application is running by going to the following URL:

----
http://localhost:9080
----

You should see the following output displayed in your browser:

----
Greetings from Spring Boot!
----

Stop the server using the following command:

----
./server stop springBoot
----

== Deploying the application to Docker

The springBootUtility thin function discussed in the previous section is especially useful when deploying your application to a Docker
container. Using Docker, you can run this thin function and run your thinned application with a few simple commands.
For more information on using Open Liberty with Docker, see the https://github.com/OpenLiberty/guide-docker[Using Docker containers to develop microservices] guide.

The `start` directory already contains a Dockerfile file that can be used to build and run your docker image. Thinning and deploying the application is done automatically.
Navigate to `start` and build the image.

----
docker build -t springboot .
----

Execute the Docker `run` command to run your Spring Boot application.

----
docker run -d --name springBootContainer -p 9080:9080 -p 9443:9443 springboot
----

Before you access your application from the browser, run the docker ps command from the command line to make sure that your container is running and didn’t crash:

----
docker ps
----

You should see an entry like the following:

----
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                            NAMES
e33532aa07d6        springboot          "/opt/ibm/docker/doc…"   7 seconds ago       Up 2 seconds        0.0.0.0:9080->9080/tcp, 0.0.0.0:9443->9443/tcp   springBootContainer
----

Now access the application at the following URL:

----
http://localhost:9080
----

You should again see the following output displayed in your browser:

----
Greetings from Spring Boot!
----

== Great work! You're done!

You installed a basic Spring Boot application to run in Open Liberty.

include::{common-includes}/finish.adoc[]
